name: CI - About Page Test

on:
  pull_request:
    branches:
      - main

jobs:
  test_about:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install Flask pytest pytest-cov codecov

      - name: Run tests - About Page
        run: pytest --cov=app test_about.py

      - name: Save coverage data
        run: mv .coverage coverage-about.info
