name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test_and_report_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install Flask pytest pytest-cov codecov

      - name: Run tests and coverage
        run: |
          pytest --cov=app test_app.py

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
#comment
#comment2